version: '3.9'

services:

  blitzDb:
    image: mysql:8.0.21
    container_name: app_blitzDb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: app_backend
    depends_on:
      blitzDb:
        condition: service_healthy
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app/backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  
  frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/frontend
    environment:
      - REACT_APP_API_HOST=backend